import { StrictMode } from 'react'
import ReactDOM from 'react-dom/client'
import { App } from './App.tsx'
import { applyPreference } from './dark-mode'

import './style.css'

applyPreference()

// biome-ignore lint/style/noNonNullAssertion: auto-generated by wxt
ReactDOM.createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
)
